### ISSUE TITLE
Controller Capability Proxies console spam

### ISSUE THREAD

**Issue by JonoColwell** [CleanroomMC/Multiblocked#89]
On starting Create: AstralEngineering, I am presented with the server every 2 seconds outputting five warnings about controllers way off in the distant reaches of the map, note this started prior to any players accessing the server
![image](https://github.com/CleanroomMC/Multiblocked/assets/8704304/dd719c57-35fe-4595-bb22-f8be4b71bb49)

Steps to reproduce:
Install Create: Arcane Engineering 0.1.6 on a dedicated server, forge version is latest
Start the server (You'll need to strip rubidium and oculus if by the time you get around to this they've not put out the server files)

Expected Behaviour: Console remains unspammed

Actual behaviour: Console is spammed per above image

**Comment by Bullzey** [comment]
I've installed a Create arcane engineering server on 0.1.7 and have the exact same issue happening which has forge version 40.2.9. and get the exact same issue. 
I've delete and redone the world folder and still the same too.
Any inside on this would be useful since there are a few of us seemingly having the same issue.

**Comment by KorewaLidesu** [comment]
Please report to this instead
https://github.com/Low-Drag-MC/Multiblocked
